<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CommentRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Paginate comments.
     *
     * @param int $page
     *
     * @return \Doctrine\ORM\Tools\Pagination\Paginator
     */
    public function getComments($page, $author)
    {
        $query = $this->createQueryBuilder('c')
                ->where('c.author = :author')
                ->setParameter('author', $author)
                ->orderBy('c.created_at', 'DESC')
                ->getQuery();

        $paginator = $this->paginate($query, $page);

        return $paginator;
    }

    /**
     * Helper paginate method.
     *
     * @param Doctrine\ORM\Query $query
     * @param int                $page  Current page (defaults to 1)
     * @param int                $limit The total number per page (defaults to 5)
     *
     * @return \Doctrine\ORM\Tools\Pagination\Paginator
     */
    public function paginate($query, $page = 1, $limit = 5)
    {
        $paginator = new Paginator($query);

        $paginator->getQuery()
            ->setFirstResult($limit * ($page - 1)) // Offset
            ->setMaxResults($limit); // Limit

        return $paginator;
    }
}
